"""Add user_id to questions

Revision ID: a740da5d60ba
Revises: f96ab18ccc17
Create Date: 2024-08-12 17:01:50.083284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a740da5d60ba'
down_revision = 'f96ab18ccc17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_user_id',  # This is the name of the constraint
            'user',        # The referred table
            ['user_id'],   # Local columns
            ['id'],        # Referred columns
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
